### ISSUE TITLE
Could bitsy be used in Android?

### ISSUE THREAD

**Issue by zhuguocheng29** [lambdazen/bitsy#17]
I have a project that want to use in-memory graph database in Android. I used to tinker graph, but I meet GC problem for a while. There fore, I want to use bitsy instead of tinkergraph. Could bitsy be used in Android?

**Comment by lambdazen** [comment]
I haven't tested on Android, but here's a quick checklist: 
- Will the data in the DB fit in memory? Bitsy uses memory-optimized data structures, but it still expects to have all the data in memory so that the traversals are fast.  
  * If the answer is no, I'd suggest a non-graph approach because the traversals get very expensive on disk irrespective of the graph database implementation. In such cases, you are better off storing larger JSON objects in a light-weight key-value DB. 
- Do you want the graph DB to be durable, i.e., store updates on filesystem so that the data is maintained across restarts? My understanding is that TinkerGraph doesn't persist data on updates. 
  * If the answer is no, you can pass no args to the BitsyGraph constructor to launch Bitsy in non-durable memory-only mode. 
  * If yes, you need to check the file system used to store the database for metadata journaling support. File systems like ext4 are OK for Bitsy, but you may encounter data loss with FAT. Based on web search, I think internal storage for Android devices is typically ext4 but SD cards might still use FAT/exFAT. 

I'll be happy to help if you run into any issues.

**Comment by zhuguocheng29** [comment]
@lambdazen
Thank you for your reply
